version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes: 
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/api-clean-node
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment: 
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./package.json:usr/src/api-clean-node/package.json
      - ./dist/:usr/src/api-clean-node/dist
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
      
